apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: book-info-request-authentication
spec:
  selector:
    matchLabels:
     app: book-info
  jwtRules:
  - issuer: "http://keycloak:8080/realms/istio"
    jwksUri: "http://keycloak:8080/realms/istio/protocol/openid-connect/certs"